<?php
/**
 * @var \Magento\Catalog\Block\Product\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Gene\BetterCheckout\ViewModel\Assets $assetViewModel
 */
$assetViewModel = $block->getAssetViewModel();
$jsAssets = $assetViewModel->getAssetsByType('js');
$cssAssets = $assetViewModel->getAssetsByType('css');
$designerStyles = $assetViewModel->getStyles();
$logo = $assetViewModel->getLogo();
$fontUrl = $assetViewModel->getFontUrl();
$fontCdnUrl = $assetViewModel->getFontCdnUrl();
$customWordings = $assetViewModel->getCustomWording();
$fontFamily = $assetViewModel->getFontFamily();

?>

<script>
    window.geneCheckout = window.geneCheckout || {};
    window.geneCheckout.magentoEdition = "<?= $escaper->escapeJs($assetViewModel->getMagentoEdition()); ?>";
    window.geneCheckout.staticPath = "<?= $escaper->escapeJs($assetViewModel->getViewFileUrl('Gene_BetterCheckout::js/checkout/dist/')) ?>";
    window.geneCheckout.logo = "<?= $escaper->escapeJs($logo); ?>";
    window.geneCheckout.belowEmailFields = window.geneCheckout.belowEmailFields || {};
    window.geneCheckout.paymentMethods = window.geneCheckout.paymentMethods || {};
    window.geneCheckout.shippingMethods = window.geneCheckout.shippingMethods || {};

    <?php if ($customWordings): ?>
        <?php foreach (json_decode($customWordings) as $key => $value): ?>
            window.geneCheckout["<?= $escaper->escapeJs($key) ?>"] = "<?= $escaper->escapeJs($value) ?>";
        <?php endforeach; ?>
    <?php endif; ?>
</script>

<link href="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Gene_BetterCheckout::css/checkout.css')) ?>" rel="stylesheet" media="all" />

<?php if ($fontCdnUrl) : ?>
    <?= $fontCdnUrl ?>
<?php elseif ($fontUrl) : ?>
    <style>
        @font-face {
            font-family: 'BetterCheckoutFont';
            src: url(<?=  $escaper->escapeUrl($fontUrl) ?>) format(<?= $escaper->escapeUrl($assetViewModel->getFontFormat($fontUrl)) ?>);
        }
    </style>
<?php endif; ?>

<?php foreach ($cssAssets as $cssAsset): ?>
    <link rel="stylesheet" media="all" href="<?= $escaper->escapeHtmlAttr($cssAsset->getUrl()); ?>">
<?php endforeach; ?>

<?php foreach ($jsAssets['main'] as $jsAsset): ?>
    <script>
        window.geneCheckout.main = "<?= $escaper->escapeJs($jsAsset->getUrl()) ?>";
    </script>
    <script defer type="module" src="<?= $escaper->escapeHtmlAttr($jsAsset->getUrl()); ?>"></script>
<?php endforeach; ?>

<script>
    window.geneCheckout.staticPath =
        window.geneCheckout.staticPath.replace(
            /(.+)\/Gene_BetterCheckout\//,
            window.geneCheckout.main.replace(/(\/Gene_BetterCheckout.+)/, '') + '/Gene_BetterCheckout/'
        );
</script>

<?php if (array_key_exists('imports', $jsAssets)): ?>
    <?php foreach ($jsAssets['imports'] as $jsAsset): ?>
        <link rel="modulepreload" href="<?= $escaper->escapeHtmlAttr($jsAsset->getUrl()); ?>">
    <?php endforeach; ?>
<?php endif; ?>

<div id="gene-better-checkout-root"
     class="full-width container"
     data-static-path="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('')) ?>"
     style="min-height: 100%; <?= $escaper->escapeHtmlAttr($designerStyles) ?>">
    <div class="loading-mask">
        <div class="loader">
            <img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
                 style="width: 50px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        </div>
    </div>
</div>
