<?php
/**
 * @var \Magento\Catalog\Block\Product\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \BlueFinch\Checkout\ViewModel\Assets $assetViewModel
 */
$assetViewModel = $block->getAssetViewModel();
$jsAssets = $assetViewModel->getAssetsByType('js');
$cssAssets = $assetViewModel->getAssetsByType('css');
$designerStyles = $assetViewModel->getStyles();
$logo = $assetViewModel->getLogo();
$fontUrl = $assetViewModel->getFontUrl();
$fontCdnUrl = $assetViewModel->getFontCdnUrl();
$customWordings = $assetViewModel->getCustomWording();
$fontFamily = $assetViewModel->getFontFamily();

?>

<script>
    window.bluefinchCheckout = window.bluefinchCheckout || {};
    window.bluefinchCheckout.magentoEdition = "<?= $escaper->escapeJs($assetViewModel->getMagentoEdition()); ?>";

    window.bluefinchCheckout.staticPath = "<?= $assetViewModel->getDistViewFileUrl('BlueFinch_Checkout::js/checkout/dist/') ?>";
    window.bluefinchCheckout.logo = "<?= $escaper->escapeJs($logo); ?>";
    window.bluefinchCheckout.belowEmailFields = window.bluefinchCheckout.belowEmailFields || {};
    window.bluefinchCheckout.paymentMethods = window.bluefinchCheckout.paymentMethods || {};
    window.bluefinchCheckout.shippingMethods = window.bluefinchCheckout.shippingMethods || {};

    <?php if ($customWordings): ?>
        <?php foreach (json_decode($customWordings) as $key => $value): ?>
            window.bluefinchCheckout["<?= $key ?>"] = "<?= $value ?>";
        <?php endforeach; ?>
    <?php endif; ?>
</script>

<link href="<?= $this->getViewFileUrl('BlueFinch_Checkout::css/checkout.css') ?>" rel="stylesheet" media="all" />

<?php if ($fontCdnUrl) : ?>
    <?= $fontCdnUrl ?>
<?php elseif ($fontUrl) : ?>
    <style>
        @font-face {
            font-family: 'BetterCheckoutFont';
            src: url(<?=  $escaper->escapeUrl($fontUrl) ?>) format(<?= $assetViewModel->getFontFormat($fontUrl) ?>);
        }
    </style>
<?php endif; ?>

<?php foreach ($cssAssets as $cssAsset): ?>
    <link rel="stylesheet" media="all" href="<?= $escaper->escapeUrl($cssAsset->getUrl()); ?>">
<?php endforeach; ?>

<?php foreach ($jsAssets['main'] as $jsAsset): ?>
    <script>
        window.bluefinchCheckout.main = "<?= $escaper->escapeUrl($jsAsset->getUrl()) ?>";
    </script>
    <script defer type="module" src="<?= $escaper->escapeUrl($jsAsset->getUrl()); ?>"></script>
<?php endforeach; ?>

<script>
    window.bluefinchCheckout.staticPath =
        window.bluefinchCheckout.staticPath.replace(
            /(.+)\/BlueFinch_Checkout\//,
            window.bluefinchCheckout.main.replace(/(\/BlueFinch_Checkout.+)/, '') + '/BlueFinch_Checkout/'
        );
</script>

<?php if (array_key_exists('imports', $jsAssets)): ?>
    <?php foreach ($jsAssets['imports'] as $jsAsset): ?>
        <link rel="modulepreload" href="<?= $escaper->escapeUrl($jsAsset->getUrl()); ?>">
    <?php endforeach; ?>
<?php endif; ?>

<div id="bluefinch-checkout-root"
     class="full-width container"
     data-static-path="<?= $escaper->escapeUrl($block->getViewFileUrl('')) ?>"
     style="min-height: 100%; <?= $designerStyles ?>">
    <div class="loading-mask">
        <div class="loader">
            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
                 style="width: 50px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        </div>
    </div>
</div>
