<?php
/**
 * @var \Magento\Catalog\Block\Product\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \BlueFinch\Checkout\ViewModel\Assets $assetViewModel
 *  @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$assetViewModel = $block->getAssetViewModel();
$jsAssets = $assetViewModel->getAssetsByType('js');
$cssAssets = $assetViewModel->getAssetsByType('css');
$designerStyles = $assetViewModel->getStyles();
$logo = $assetViewModel->getLogo();
$fontUrl = $assetViewModel->getFontUrl();
$fontCdnUrl = $assetViewModel->getFontCdnUrl();
$customWordings = $assetViewModel->getCustomWording();
$fontFamily = $assetViewModel->getFontFamily();

?>

<?php $scriptString = <<<script

    window.bluefinchCheckout = window.bluefinchCheckout || {};
    window.bluefinchCheckout.magentoEdition = "{$escaper->escapeJs($assetViewModel->getMagentoEdition())}";

    window.bluefinchCheckout.staticPath = "{$escaper->escapeJs($assetViewModel->getDistViewFileUrl('BlueFinch_Checkout::js/checkout/dist/'))}";
    window.bluefinchCheckout.logo = "{$escaper->escapeJs($logo)}";
    window.bluefinchCheckout.belowEmailFields = window.bluefinchCheckout.belowEmailFields || {};
    window.bluefinchCheckout.paymentMethods = window.bluefinchCheckout.paymentMethods || {};
    window.bluefinchCheckout.shippingMethods = window.bluefinchCheckout.shippingMethods || {};

script;
    if ($customWordings):
        foreach (json_decode($customWordings) as $key => $value):
            $scriptString .= <<<script
    window.bluefinchCheckout["{$escaper->escapeJs($key)}"] = "{$escaper->escapeJs($value)}";

script;
        endforeach;
    endif;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<link href="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('BlueFinch_Checkout::css/checkout.css')) ?>" rel="stylesheet" media="all" />

<?php if ($fontCdnUrl): ?>
    <?= $fontCdnUrl ?>
<?php elseif ($fontUrl): ?>
    <style>
      @font-face {
        font-family: 'BlueFinchCheckoutFont';
        src: url(<?=  $escaper->escapeUrl($fontUrl) ?>) format(<?= $assetViewModel->getFontFormat($fontUrl) ?>);
      }
    </style>
<?php endif; ?>

<?php foreach ($cssAssets as $cssAsset): ?>
    <link rel="stylesheet" media="all" href="<?= $escaper->escapeHtmlAttr($cssAsset->getUrl()); ?>">
<?php endforeach; ?>

<?php
$mainJsAsset = $jsAssets['main'][0];
$scriptString = <<<script

    window.bluefinchCheckout.main = "{$escaper->escapeJs($mainJsAsset->getUrl())}";

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script defer type="module" src="<?= $escaper->escapeHtmlAttr($mainJsAsset->getUrl()); ?>"></script>

<?php
$scriptString = <<<script

    window.bluefinchCheckout.staticPath =
        window.bluefinchCheckout.staticPath.replace(
            /(.+)\/BlueFinch_Checkout\//,
            window.bluefinchCheckout.main.replace(/(\/BlueFinch_Checkout.+)/, '') + '/BlueFinch_Checkout/'
        );

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<?php if (array_key_exists('imports', $jsAssets)): ?>
    <?php foreach ($jsAssets['imports'] as $jsAsset): ?>
        <link rel="modulepreload" href="<?= $escaper->escapeHtmlAttr($jsAsset->getUrl()); ?>">
    <?php endforeach; ?>
<?php endif; ?>

<div id="bluefinch-checkout-root"
     class="full-width container"
     data-static-path="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('')) ?>"
     style="min-height: 100%; <?= $escaper->escapeHtmlAttr($designerStyles) ?>">
    <div class="loading-mask">
        <div class="loader">
            <img src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
                 style="width: 50px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        </div>
    </div>
</div>
