<?php
/**
 * Override core template file to remove requirements on jQuery and Magento.
 * @var \Magento\GoogleTagManager\Block\GtagGa $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\GoogleTagManager\ViewModel\TagManagerConfig $gtmConfig
 */

 use Magento\GoogleTagManager\Model\Config\TagManagerConfig;

$gtmConfig = $block->getData('view_model');
$accountType = $gtmConfig->getAccountType();
$gtmAccountId = $gtmConfig->getContainerId();
$gapAccountId = $gtmConfig->getMeasurementId();
switch ($accountType) {
    case TagManagerConfig::TYPE_TAG_MANAGER:
        if (!empty($gtmAccountId)) {
            ?>
            <!-- GOOGLE TAG MANAGER -->
            <script defer src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Gene_BetterCheckout::js/google-tag-manager.js')) ?>"></script>
            <script defer>
                /**
                 * @param {Object} config
                 */
                (function (config) {
                    // If the init is available call it otherwise wait until it's available.
                    window.geneInitGtm
                        ? window.geneInitGtm(config)
                        : document.addEventListener('geneGa:inited', function () {
                            window.geneInitGtm(config);
                        });

                    // If the User changes their cookie preference.
                    document.addEventListener('user:allowed:save:cookie', function () {
                        window.geneInitGtm(config);
                    });
                })(<?= $escaper->escapeJs($block->getTagManagerData()) ?>)
            </script>
            <!-- END GOOGLE TAG MANAGER -->
            <?php
        }
        break;
    case TagManagerConfig::TYPE_ANALYTICS4:
        if (!empty($gapAccountId)) {
            ?>
            <!-- BEGIN GOOGLE ANALYTICS 4 CODE -->
            <script defer src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Gene_BetterCheckout::js/google-analytics.js')) ?>"></script>
            <script defer>
                /**
                 * @param {Object} config
                 */
                (function (config) {
                    // If the init is available call it otherwise wait until it's available.
                    window.geneInitGtm
                        ? window.geneInitGtm(config)
                        : document.addEventListener('geneGa:inited', function () {
                            window.geneInitGtm(config);
                        });

                    // If the User changes their cookie preference.
                    document.addEventListener('user:allowed:save:cookie', function () {
                        window.geneInitGtm(config);
                    });
                })(<?= $escaper->escapeJs($block->getAnalyticsData()) ?>)
            </script>
            <!-- END GOOGLE ANALYTICS 4 CODE -->
            <?php
        }
        break;
}
