<?php
/**
 * Order success footer
 * @var \Magento\Checkout\Block\Onepage\Success $block
 * @var Magento\Framework\Escaper $escaper
 */

/** @var \BlueFinch\Checkout\ViewModel\CheckoutSuccess $orderViewViewModel */
$orderViewViewModel = $block->getData('order_view_view_model');

if ($orderViewViewModel) {
  /** @var \Magento\Sales\Model\Order $order */
    $order = $orderViewViewModel->getLastOrder();
}
?>

<div class="checkout-success-container">
    <p class="summary-title"><?= $escaper->escapeHtml(__('Order Summary')) ?></p>
    <hr>
    <div class="checkout-success-totals">
        <div class="checkout-success-summary-columns">
            <span><?= $escaper->escapeHtml(__('Subtotal')) ?></span>

            <?php if ($orderViewViewModel->displayCartPricesInclTax()): ?>
                <span><?= $escaper->escapeHtml($order->formatPrice($order->getSubtotalInclTax())) ?></span>
            <?php endif; ?>

            <?php if ($orderViewViewModel->displayCartPricesExclTax()): ?>
                <span><?= $escaper->escapeHtml($order->formatPrice($order->getSubtotal())) ?></span>
            <?php endif; ?>
        </div>
        <div class="checkout-success-summary-columns">
            <span><?= $escaper->escapeHtml($order->getShippingDescription()) ?></span>
            <?php if ($orderViewViewModel->displayShippingPricesInclTax()): ?>
                <span><?= $escaper->escapeHtml($order->formatPrice($order->getShippingInclTax())) ?></span>
            <?php endif; ?>
            <?php if ($orderViewViewModel->displayShippingPricesExclTax()): ?>
                <span><?= $escaper->escapeHtml($order->formatPrice($order->getShippingAmount())) ?></span>
            <?php endif; ?>
        </div>
        <?php if ((float)$order->getDiscountAmount()): ?>
            <div class="checkout-success-summary-columns">
                <span><?= $escaper->escapeHtml(__('Discount')) ?></span>
                <span><?= $escaper->escapeHtml($order->formatPrice($order->getDiscountAmount())) ?></span>
            </div>
        <?php endif; ?>
        <?php if ((float)$order->getGiftCardsAmount()): ?>
            <div class="checkout-success-summary-columns">
                <span><?= $escaper->escapeHtml(__('Gift Card')) ?></span>
                <span><?= '-' . $escaper->escapeHtml($order->formatPrice($order->getGiftCardsAmount())) ?></span>
            </div>
        <?php endif; ?>
        <div class="checkout-success-summary-columns total-container">
            <span><strong><?= $escaper->escapeHtml(__('Total to Pay')) ?></strong></span>
            <span><strong><?= $escaper->escapeHtml($order->formatPrice($order->getGrandTotal())) ?></strong></span>
        </div>
        <hr>
    </div>

    <div class="checkout-success-items">
        <?php foreach ($order->getItems() as $item): ?>
            <?php
            if ($item->getParentItemId()) {
                continue;
            }
            ?>
            <?php $image = $orderViewViewModel === null ? null : $orderViewViewModel->getOrderItemProductImageUrl($item); ?>
            <div class="checkout-success-summary-columns">
                <img class="single-order__item-image" src="<?= $escaper->escapeHtmlAttr($image) ?>"
                     alt="<?= $escaper->escapeHtmlAttr($item->getName()) ?>">
                <div>
                    <p><?= $escaper->escapeHtml($item->getName()) ?></p>
                    <?= $escaper->escapeHtml($order->formatPrice($item->getPriceInclTax())) ?>
                    <p class="qty">
                        <?= $escaper->escapeHtml(__('Quantity: ')) ?>
                        <?= $escaper->escapeHtml((int) $item->getQtyOrdered()) ?>
                    </p>
                </div>
            </div>
            <hr>
        <?php endforeach; ?>
    </div>

    <?php if ($order->getShippingAddress()): ?>
        <div class="checkout-success-summary-columns checkout-success-delivery-container">
            <div>
                <p class="shipping-title"><?= $escaper->escapeHtml(__('Shipping Address')) ?></p>
                <?= $escaper->escapeHtml($orderViewViewModel->getFormattedAddress($order->getShippingAddress())) ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($order->getShippingDescription()): ?>
        <div class="checkout-success-summary-columns checkout-success-shipping-container">
            <div>
                <p class="shipping-title"><?= $escaper->escapeHtml(__('Shipping Method')) ?></p>
                <p><?= $escaper->escapeHtml($order->getShippingDescription()) ?></p>
            </div>
        </div>
    <?php endif; ?>
</div>
