name: Generate dist for hotfix branch

on:
  push:
    branches:
      - "hotfix/*"  # This triggers the action on any branch that starts with "hotfix/"

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    env:
      SOURCE_BRANCH: ${{ github.ref_name }}    # Capture the branch name (e.g., hotfix/abc)
      DIST_BRANCH: ${{ github.ref_name }}-dist # Create the dist branch name dynamically (e.g., hotfix/abc-dist)

    steps:

      - name: Prepare git
        shell: bash
        run: |
          git config --global user.name "github-action[bot]"
          git config --global user.email "github-action[bot]@users.noreply.github.com"

      - name: Check out the src branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SOURCE_BRANCH }}  # Check out the dynamic source branch (hotfix/abc)

      - name: Generate dist
        shell: bash
        run: |
          set -v
          
          git checkout ${{ env.DIST_BRANCH }} || git checkout -b ${{ env.DIST_BRANCH }}  # Create or switch to the dist branch
          
          git config --global pull.rebase false
          git fetch --unshallow || true
          
          git merge origin/${{ env.SOURCE_BRANCH }} --no-edit --verbose
          
          # Store the sha that matches to the dist, we can then back track to the "clean" version without dist files
          # Can be useful in future for convenient hotfixing specifically tagged versions
          echo "${{ github.sha }}" > .github/sha.txt
          git add -f .github/sha.txt
          
          cd view/frontend/web/js/checkout/
          npm ci
          npm run build
          git add -f ./dist
          git commit --allow-empty -am "[bot] generate dist ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
          git push origin ${{ env.DIST_BRANCH }}
