name: Generate dist

on:
  push:
    branches:
      - automate-workflow # todo swap to `main` and add one for `develop`

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    steps:

      - name: Prepare git
        shell: bash
        run: |
          git config --global user.name "github-action[bot]"
          git config --global user.email "github-action[bot]@users.noreply.github.com"

      - name: Check out the src branch
        uses: actions/checkout@v3
        with:
          ref: automate-workflow

      - name: Check out the dist branch
        uses: actions/checkout@v3
        with:
          ref: automate-workflow-dist

      - name: Generate dist
        shell: bash
        run: |
          set -v
          
          git checkout automate-workflow-dist
          
          git config --global pull.rebase false
          git fetch --unshallow || true
          
          git merge origin/automate-workflow --no-edit --verbose
          
          # Store the sha that matches to the dist, we can then back track to the "clean" version without dist files
          # Can be useful in future for convenient hotfixing specifically tagged versions
          echo "${{ github.sha }}" > .github/sha.txt
          git add -f .github/sha.txt
          
          cd view/frontend/web/js/checkout/
          npm ci
          npm run build
          git add -f ./dist
          git commit --allow-empty -am "[bot] generate dist ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
          git push

